<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1mqs00q\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1mqs00q/appProdProjectContainer.php') {
    touch(__DIR__.'/Container1mqs00q.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container1mqs00q\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container1mqs00q\appProdProjectContainer(array(
    'container.build_hash' => '1mqs00q',
    'container.build_id' => '47770b5b',
    'container.build_time' => 1519471044,
));
