<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWla1zj3\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWla1zj3/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWla1zj3.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWla1zj3\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWla1zj3\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Wla1zj3',
    'container.build_id' => '44f4d1f1',
    'container.build_time' => 1519650680,
));
